import { readFileSync, writeFileSync, mkdirSync, cpSync } from 'node:fs';
import { resolve, dirname } from 'node:path';

const repo=resolve(process.cwd());
const out=resolve(process.argv[2]||'dist-v2');
const base=JSON.parse(readFileSync(resolve(repo,'catalog/games.json'),'utf8'));
const overrides=JSON.parse(readFileSync(resolve(repo,'catalog/overrides.json'),'utf8'));
const overrideMap=new Map(overrides.map(x=>[x.id,x]));
const merged=base.map(x=>overrideMap.get(x.id)??x);

const lex={
 tiny:'미니어처',detective:'탐정 수첩',grid:'증거 격자',bridge:'목조 다리',count:'번호 표지',clockwork:'황동 시계장치',repair:'정비 공구',pipe:'구리 파이프',garden:'온실 화분',daily:'오늘의 도장',clue:'단서 카드',board:'코르크 보드',fold:'접는 선',map:'여행 지도',knot:'계류 매듭',harbor:'항만 부두',parking:'주차 차량',rooftop:'옥상 난간',shadow:'벽 그림자',cabinet:'진열장',number:'숫자 다이얼',vault:'금고 문',tile:'모자이크 타일',museum:'전시대',magnet:'자기 코일',boxes:'철제 상자',shape:'퍼즐 조각',packing:'포장 상자',conveyor:'컨베이어',colors:'색상 센서',signal:'신호기',tower:'중계탑',orbit:'궤도 링',courier:'배달 소포',pigeon:'비둘기',gravity:'중력 스위치',laundry:'양말 바구니',paper:'종이',boat:'종이배',rapids:'급류',neon:'네온 광선',ricochet:'반사 벽',balloon:'열기구',taxi:'승객 승강장',pendulum:'진자 갈고리',thief:'도둑 가면',runner:'러너 부츠',ice:'얼음',parcel:'배송 상자',beat:'박자 원',bounce:'점프 발판',hangul:'한글 타일',relay:'끝말 카드',missing:'빠진 글자',signboard:'낡은 간판',emoji:'이모지 카드',dictionary:'사전',typing:'키보드',escape:'탈출 문',reverse:'역방향 단서',four:'네 개',place:'장소 핀',syllable:'음절 블록',factory:'공장 벨트',sentence:'문장 부품',category:'분류 깃발',sprint:'결승선',riddle:'수수께끼 두루마리',desk:'책상',aquarium:'유리 수조',moon:'달빛',bakery:'오븐 빵',cloud:'구름',sheep:'구름 양',ranch:'하늘 목장',night:'야간 조명',bookshop:'책장',firefly:'반딧불',terrarium:'유리 정원',island:'작은 섬',post:'우편 봉투',office:'업무 데스크',mini:'미니어처',tea:'찻잎',cart:'이동 카트',pocket:'소형 장비',observatory:'망원경 돔',traffic:'교차로',six:'퇴근 시계',dispatcher:'관제 무전기',food:'재료 상자',truck:'푸드트럭',rush:'주문 티켓',hotel:'객실 열쇠',power:'전력 코어',festival:'축제 게이트',queue:'대기 줄',weather:'기상 레이더',station:'관측소',recycling:'재활용 벨트',plant:'분류 공장',newsroom:'뉴스룸',deadline:'마감 시계',airport:'공항 전광판',gate:'탑승 게이트',manager:'관리 보드',castle:'성벽',defense:'방어 포탑',dungeon:'던전',shopkeeper:'상점 주인',space:'우주 돔',colony:'식민지',seven:'7일 기록',train:'열차',timetable:'시간표',town:'도시 구역',waterworks:'급수탑',forest:'숲',ranger:'산림 감시탑',five:'다섯',minute:'분침',kingdom:'작은 왕국',cargo:'화물 컨테이너',port:'물류 부두',restaurant:'레스토랑 테이블',shift:'근무표',rescue:'구조 헬기',planner:'구조 지도',three:'세 장',card:'행동 카드',knight:'기사',dice:'주사위',alchemist:'연금술 가마솥',hex:'육각 보드',war:'영역 깃발',robot:'로봇 부품',draft:'드래프트 카드',arena:'경기장',spell:'마법 룬',potion:'포션 병',duel:'결투대',bounty:'현상금 포스터',route:'경로 지도',ten:'열 개',survival:'생존 모닥불',chess:'체스 말',relic:'고대 유물',ghost:'유령',heist:'금고 탈출',keyboard:'키보드 선수',sumo:'스모 링',one:'한 개',button:'입력 버튼',fencing:'펜싱 검',split:'분할 화면',tank:'탱크',rhythm:'리듬 원',tug:'줄다리기 로프',goal:'골대',line:'라인',reaction:'반응 신호',chef:'셰프',bluff:'거짓 라벨',cooperative:'협동 신호',switchboard:'배전반',two:'두 명',person:'플레이어',maze:'미로 벽',pass:'전달 카드',phone:'휴대폰',last:'막차 표',bus:'버스',home:'귀가 정류장',day:'하루',mayor:'시장 집무실',radio:'무전기',operator:'통신 기록',neighborhood:'동네 지도',mystery:'사건 봉투',interview:'면접 질문',rpg:'능력치 카드',debug:'디버거',budget:'예산 토큰',quest:'월말 보스',language:'외국어 메뉴',cafe:'카페 주문',memory:'기억 카드',palace:'기억 궁전',hundredth:'백 번째',door:'황금 문'
};
const categoryObjects={Logic:['단서 패널','힌트 램프','정답 기록','레벨 도장'],Spatial:['공간 도면','회전 손잡이','격자 보드','완료 스탬프'],Arcade:['점수 전광판','콤보 링','위험 표지','부스트 아이콘'],Word:['글자 카드','힌트 전구','사전 탭','정답 종'],Cozy:['따뜻한 조명','수집 도감','단골 기록','작은 선반'],Management:['업무 보드','자원 게이지','대기 줄','근무 보고서'],Strategy:['전략 지도','행동 카드','자원 토큰','턴 표시'],Cards:['카드 덱','에너지 보석','턴 카운터','승리 문장'],Party:['왼쪽 선수','오른쪽 선수','라운드 종','승리 점수판'],Story:['선택 카드','상태 게이지','장면 기록','결말 봉투']};
const palettes={Logic:['#173a46','#e7d9b4','#ee6b45','#0c2028'],Spatial:['#3f334d','#e8decb','#d69e2e','#201827'],Arcade:['#0e2749','#e6e7d5','#20c7c9','#07111f'],Word:['#4b2b3d','#f2e7d3','#e4572e','#25151e'],Cozy:['#31584a','#f4e9d1','#d99058','#172a23'],Management:['#263948','#e6e1d5','#e2583e','#111d25'],Strategy:['#3f4326','#eee2c6','#c26b38','#202313'],Cards:['#34294d','#e9dfc8','#b68cff','#1b1428'],Party:['#20243d','#f3e6c9','#ff5d5d','#0e1122'],Story:['#2b3542','#eee5d8','#d67b42','#151b22']};
const roles={deduction:'현장 추리관',network:'망 연결 기술자',gear:'정밀 정비사',spatial:'공간 설계자',arcade:'현장 조종사',rhythm:'리듬 조종사',word:'언어 해결사',cozy:'작은 공간 운영자',management:'현장 관리자',cards:'전략 지휘관',duel:'로컬 경기 선수',story:'이야기 속 결정자',memory:'기억 궁전 안내자'};
const verbs={deduction:['단서 비교','후보 제거','정답 지목'],network:['노드 전환','경로 연결','전체 활성화'],gear:['장치 회전','표식 정렬','기계 가동'],spatial:['타일 이동','빈칸 활용','배치 완성'],arcade:['좌우 이동','대상 수집','위험 회피'],rhythm:['박자 대기','정확히 탭','콤보 유지'],word:['문제 읽기','낱말 선택','연속 정답'],cozy:['상태 확인','작업 선택','공간 성장'],management:['수요 확인','자원 배분','턴 마감'],cards:['카드 선택','자원 계산','상대 대응'],duel:['신호 대기','버튼 입력','라운드 선점'],story:['상황 읽기','선택 결정','상태 관리'],memory:['카드 공개','위치 기억','짝 맞추기']};
function mode(id){if([6,10,15,36,40].includes(id))return'deduction';if([7,9,19,20].includes(id))return'network';if([8,14,17].includes(id))return'gear';if(id>=11&&id<=18)return'spatial';if(id>=21&&id<=29)return'arcade';if(id===30)return'rhythm';if(id>=31&&id<=39)return'word';if(id>=41&&id<=50)return'cozy';if(id>=51&&id<=60)return'management';if(id>=61&&id<=80)return'cards';if(id>=81&&id<=90)return'duel';if(id===99)return'memory';return'story'}
function category(id,raw){if(id>=61&&id<=70)return'Strategy';if(id>=71&&id<=80)return'Cards';if(id>=81&&id<=90)return'Party';if(id>=91)return'Story';return raw}
function materials(game){const tokens=game.slug.replace(/^\d{3}-/,'').split('-');const cat=category(game.id,game.category);const list=tokens.map(t=>lex[t]).filter(Boolean);for(const x of categoryObjects[cat]||categoryObjects.Story)if(!list.includes(x))list.push(x);while(list.length<8)list.push(`${game.title} 전용 소재 ${list.length+1}`);return list.slice(0,10)}
const custom={1:{slug:'001-arrow-harbor',title:'Arrow Harbor',category:'Logic',description:'신호 부표를 돌려 화물선을 항구까지 유도합니다.'},2:{slug:'002-harbor-lost-found',title:'Harbor Lost & Found',category:'Hidden Object',description:'어시장·창고·부두에서 신고된 분실물을 찾습니다.'},3:{slug:'003-lightkeeper',title:'Lightkeeper',category:'Logic',description:'거울탑을 돌려 모든 항로 비콘에 빛을 연결합니다.'},4:{slug:'004-one-stroke-courier',title:'One-Stroke Courier',category:'Logic',description:'도시의 모든 도로를 한 번씩만 달려 배달합니다.'},5:{slug:'005-color-customs',title:'Color Customs',category:'Logic',description:'컨테이너 정보를 읽고 세관 게이트로 분류합니다.'}};
const games=merged.map(raw=>{if(custom[raw.id])return{...custom[raw.id],id:raw.id,path:`/Play100/games/${custom[raw.id].slug}/`,custom:true};const cat=category(raw.id,raw.category),m=mode(raw.id),objects=materials({...raw,category:cat});return{...raw,status:'playable',path:`/Play100/games/${raw.slug}/`,custom:false,category:cat,mode:m,objects,environments:[`${objects[0]}이 중심인 초반 구역`,`${objects[1]}과 ${objects[2]}가 겹치는 중간 구역`,`${objects[3]} 위험이 커지는 야간 구역`],role:roles[m],verbs:verbs[m],palette:palettes[cat]||palettes.Story,stages:5,duration:raw.duration||'2–8 min'}});
mkdirSync(out,{recursive:true});mkdirSync(resolve(out,'v2'),{recursive:true});cpSync(resolve(repo,'prototype-v2/style.css'),resolve(out,'v2/style.css'));cpSync(resolve(repo,'prototype-v2/engine.js'),resolve(out,'v2/engine.js'));writeFileSync(resolve(out,'v2/catalog.js'),`window.PLAY100_CATALOG=${JSON.stringify(games)};\n`);
const portal=`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#102630"><meta name="description" content="PLAY100 — 제목과 세계관, 조작이 연결된 오리지널 브라우저 게임 100개."><title>PLAY100 — 100 Browser Games</title><link rel="stylesheet" href="/Play100/v2/style.css"></head><body><div class="portal"><header class="topbar"><a class="brand" href="/Play100/"><i></i>PLAY100</a><div class="top-meta"><span>100 ORIGINAL GAMES</span><a href="https://github.com/beerAndNacho/Play100">GITHUB</a></div></header><section class="portal-hero"><div class="portal-copy"><div class="eyebrow">PLAYABLE WEB ARCADE · 001—100</div><h1>제목이<br><em>게임이</em><br>됩니다.</h1><p>추상 도형에 이름만 붙이지 않습니다. 장소, 역할, 사물, 조작과 피드백이 제목의 약속을 실제 플레이로 이어갑니다.</p></div><div class="daily"><div class="daily-card" id="daily"></div></div></section><main class="catalog"><div class="catalog-head"><div><div class="eyebrow">MASTER GAME INDEX</div><h2>게임 100개</h2></div><input class="search" id="search" type="search" placeholder="제목·소재·장르 검색"></div><div class="tabs" id="tabs"></div><div id="list"></div></main></div><script src="/Play100/v2/catalog.js"></script><script>const C=window.PLAY100_CATALOG,$=s=>document.querySelector(s),cats=['All',...new Set(C.map(g=>g.category))];let cat='All',q='';const day=C[(new Date().getDate()+new Date().getMonth()*31)%C.length];$('#daily').innerHTML='<div class="eyebrow">TODAY · GAME-'+String(day.id).padStart(3,'0')+'</div><h2>'+day.title+'</h2><p>'+day.description+'</p><a href="'+day.path+'">게임 시작 →</a>';function tabs(){$('#tabs').innerHTML=cats.map(x=>'<button class="tab '+(x===cat?'on':'')+'" data-c="'+x+'">'+x+'</button>').join('');document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{cat=b.dataset.c;tabs();list()})}function list(){const n=q.trim().toLowerCase();$('#list').innerHTML=C.filter(g=>(cat==='All'||g.category===cat)&&(!n||(g.title+' '+g.description+' '+g.category+' '+(g.objects||[]).join(' ')).toLowerCase().includes(n))).map(g=>'<a class="game-row" href="'+g.path+'"><span class="game-no">GAME-'+String(g.id).padStart(3,'0')+'</span><h3>'+g.title+'</h3><span class="game-cat">'+g.category+'</span><p>'+g.description+'</p><span class="game-go">PLAY →</span></a>').join('')}$('#search').oninput=e=>{q=e.target.value;list()};tabs();list();</script></body></html>`;writeFileSync(resolve(out,'index.html'),portal);
const loader=g=>`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="robots" content="index,follow"><meta name="theme-color" content="#102630"><title>${g.title} — PLAY100 GAME-${String(g.id).padStart(3,'0')}</title><meta name="description" content="${g.description}"><link rel="stylesheet" href="/Play100/v2/style.css"></head><body><script>window.PLAY100_SLUG=${JSON.stringify(g.slug)};</script><script src="/Play100/v2/catalog.js"></script><script src="/Play100/v2/engine.js"></script></body></html>`;
for(const g of games.filter(x=>x.id>=6)){const dir=resolve(out,'games',g.slug);mkdirSync(dir,{recursive:true});writeFileSync(resolve(dir,'index.html'),loader(g))}
writeFileSync(resolve(out,'v2/manifest.json'),JSON.stringify({count:games.length,generated:new Date().toISOString(),modes:[...new Set(games.filter(x=>x.mode).map(x=>x.mode))]},null,2));console.log(`generated ${games.length} catalog entries and ${games.filter(x=>x.id>=6).length} shared-engine pages`);
